### ISSUE TITLE
figure

### ISSUE THREAD

**Issue by FAPLAP** [ROSB/Site-Mags#10]
Исправить галерею.

**Comment by SpartakN** [comment]
А что там за проблема? Разъезжается галерея но не всегда? Только на СиТ? Можешь скинуть url глючных статей?

**Comment by FAPLAP** [comment]
Помнишь в последний день перед отпуском обнаружилось что галерея в новости и в компании не расползается, а статьи при этом работают нормально.
Обнаружилось, что в статьях стоит "затычка под IE" которую ты (вроде) забыл убрать (хотя зачем ее было убирать не помню).
Покопавшись ты сказал что обновилась библиотека. И теперь галерея "поломалась", но случайным образом именно та затычка под IE помогла. Так как чинить по нормальному времени не было, то быстро поставили ту затычку (у тебя в комментарии в коде так и написано - что то для IE) на страницы компаний и новостей.

**Comment by FAPLAP** [comment]
https://os1.ru/company/10
https://os1.ru/event/17488-teoriya-bez-praktiki-mertva-praktika-bez-teorii-slepa

**Comment by SpartakN** [comment]
Это я помню, и про версию, и про костыль IE11. Но где именно галерея разъезжается - не помню. По твоим 2-м ссылкам у меня всё нормально.
![Вот пример](https://user-images.githubusercontent.com/7965891/42738559-4c1f616e-888e-11e8-9aed-4bcbdff18670.png)

**Comment by FAPLAP** [comment]
Так мы поставили костыль который был только в Статьях, в Новости и Компании. Так что теперь костыль везде работает. Так рано или поздно костыль надо исправлять, мы так и не поняли что там в библиотеке поменялось, что галерея стала расползаться, отложили на потом.

**Comment by FAPLAP** [comment]
Возможно это проявление этого же бага.
На сайте ГП в статьях Новой верстки Старого образца (#2) также figure разворачивается, но не в бок, а вниз. 
Возможно вниз это потому что сам сайт ГП не позволяет вбок. Тогда это тот же глюк и мы забыли  в этот случай поставить костыль. Либо это что то новое. Попробую проверить другие статьи #2 всех сайтов.
http://www.gruzovikpress.ru/article/2398-sovremennye-tramvai-sochlenennye-nizkopolnye-vmestitelnye/
![image](https://user-images.githubusercontent.com/41141329/43074024-68fee236-8e84-11e8-8af6-cee6257e1813.png)

**Comment by FAPLAP** [comment]
На ОС та же фигня
https://os1.ru/article/4457-nujny-nadejnye-furgony-i-prochnye-bortovye-nadstroyki-togda-vam-v-tsttm-vybiraya-furgon

Может проблема в подгрузке каких то компонентов - скрипты/css

**Comment by SpartakN** [comment]
Это совсем другая проблема. Уже исправил.

**Comment by SpartakN** [comment]
На СИТ все костыли убрал. У меня IE11 показывает всё нормально.
На ОС костыль оставил. Там IE11 ломается.
Если будет слетать ширина, то выкладывай сюда ссылки.

**Comment by FAPLAP** [comment]
А что с галереей? На СиТ проверил, не расползается. Ты что то поправил в ней или мы первоначально не правильно в причине разобрались?

**Comment by SpartakN** [comment]
Обновил только библиотеку галереи. Причем только на СиТе. И полностью убрал
все костыли на СиТе.

ср, 25 июл 2018 г., 9:38 FAPLAP <notifications@github.com>:
