### ISSUE TITLE
Вопросы по различным письмам в почте admin

### ISSUE THREAD

**Issue by FAPLAP** [ROSB/Site-Mags#16]
1. DHL
![image](https://user-images.githubusercontent.com/41141329/42940078-d81186dc-8b60-11e8-9432-df102c76ed54.png)

**Comment by FAPLAP** [comment]
2. nic.ru нашел вирус в baker.rosb.ru
=====================
Уважаемый клиент!

В результате антивирусной проверки вашего сайта baker.rosb.ru в относящихся к нему файлах обнаружен подозрительный программный код.
Отчет о проверке доступен в разделе "Безопасность" -> "История операций" панели управления хостингом.

Для автоматического устранения уязвимостей и вредоносного кода подключите дополнительную услугу "Антивирусная защита".

Подробнее об антивирусной защите: https://www.nic.ru/catalog/services/antivirus

**Comment by SpartakN** [comment]
1. DHL - очень похоже на фишинг. Думаю, ссылка, куда ведёт кнопка вообще левая.
Да, проверил письмо. Обман.

**Comment by SpartakN** [comment]
2. baker
[сообщение RU-Center](https://www.nic.ru/hcp2/sites/baker.rosb.ru/security/antivirus/scan/17566138/?licenses)
Там файл PHPInfo, который выдаёт подробную информацию о хостинге и PHP. Т.к. сайт не нужен, отключил его.
