### ISSUE TITLE
Баннеры Выставок на сайте ОС

### ISSUE THREAD

**Issue by FAPLAP** [ROSB/Site-Mags#18]
На сайте ОС в разделе выставки справа скопилось много баннеров.
https://os1.ru/magazine
Решил перенести часть из модуля  Правая колонка в модуль Низ сайта (Desc). 
http://mag.rosb.ru/Unit/Edit/10969/

Для оформления решил использовать стили из Главной страницы сайта СиТ. Похоже эти классы на ОС не пашут. Как раскидать там баннеры в 1-2 строчки по 4 шт. в строке?
![image](https://user-images.githubusercontent.com/41141329/43328417-995a4dc2-91c6-11e8-944c-f7169c79ae8b.png)

**Comment by SpartakN** [comment]
Там надо использовать классические классы, типа: `grid-x grid-margin-x`  и `cell small-3`

И вот это не нужно `<div class="" style="grid-column: 3 / span 6; grid-row-start: 1;">`

```
<div class="grid-x grid-margin-x-small">
    <a href="http://www.nodig-moscow.ru/?utm_source=nodig-moscow_rosbusiness&amp;utm_medium=nodig-moscow_rosbusiness_banner&amp;utm_campaign=nodig-moscow_rosbusiness_banner_240" class="cell small-3 block block--auto"><img src="/Files/abc/exb-nodig-r240.jpg"></a>
    <a href="http://www.ecwatech.ru/?utm_source=ecwatech_rosbusiness&amp;utm_medium=ecwatech_rosbusiness_banner&amp;utm_campaign=ecwatech_rosbusiness_banner_240" class="cell small-3 block block--auto"><img src="/Files/abc/exb-ecwatech240.jpg"></a>
    <a href="http://www.ecwatech.ru/?utm_source=ecwatech_rosbusiness&amp;utm_medium=ecwatech_rosbusiness_banner&amp;utm_campaign=ecwatech_rosbusiness_banner_240" class="cell small-3 block block--auto"><img src="/Files/abc/exb-ecwatech240.jpg"></a>
</div>
```

**Comment by SpartakN** [comment]
Там надо использовать классические классы, типа: grid-x grid-margin-x  и cell small-3
