### ISSUE TITLE
Аккаунт Паши в админке и в RB

### ISSUE THREAD

**Issue by FAPLAP** [ROSB/Site-Mags#21]
Пашка уволился. Так что у нас новый дизайнер.
1. Аккаунт в админке  - наверно стоит либо удалить, либо тоже в рид-онли перевести.
2. Аккаунт в RB для нового дизайнера.
Пока человек работает под аккаунтом Паши.
Нужны:
 - сохранение всех настроек на пашиной машине;
 - новые инициалы (Тищенко Евгения Викторовна);
 - почта.
Какие есть варианты? Создать под нее новый или переименовать пашин?

**Comment by SpartakN** [comment]
Права на учётку в Mag нужно проставить после создания.
